// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SomaliEbay.Models;

namespace SomaliEbay.Migrations
{
    [DbContext(typeof(SomaliEbayDbContext))]
    partial class SomaliEbayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SomaliEbay.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ISpaid");

                    b.Property<int?>("ProductId");

                    b.Property<int>("Qty");

                    b.Property<decimal>("TotalCost");

                    b.Property<decimal>("TotalPaid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("SomaliEbay.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Discount");

                    b.Property<decimal>("Price");

                    b.Property<string>("ProducName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<byte[]>("ProductImage");

                    b.Property<int>("Qty");

                    b.HasKey("Id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("SomaliEbay.Models.Order", b =>
                {
                    b.HasOne("SomaliEbay.Models.Product", "product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId");
                });
#pragma warning restore 612, 618
        }
    }
}
